### ISSUE TITLE
Error: Cannot find module 'next-aws-lambda'

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-nextjs-plugin#124]
# Description
When I use new version of the plugin (v 2.3.2), I get the following error when I try run on AWS (this is happening in my custom lambda)

```Error: Cannot find module 'next-aws-lambda'```

Note: I also installed `next-aws-lambda`. This is strange, because it runs perfectly locally.

**Comment by barrysteyn** [comment]
Also, my code is not the root folder... rather, it's a client folder. I have put my serverless.yml file in that (i.e. the client) folder.

**Comment by me4502** [comment]
This is due to the plugin looking for next-aws-lambda in the same folder when copying it. I noted that in another issue, and the official response was https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/75#issuecomment-493856802

As forcing it to install in the leaf doesn't work reliably, I've been patching the plugin to just include the `../` in the path. Realistically this project should be updated to resolve the actual module and grab it from there, rather than just assuming it's in the same location.

**Comment by barrysteyn** [comment]
Thanks for the reply. Can you do me a favor and share some code of your
patch?
-- 

Barry Steyn
Blog <http://doctrina.org> LinkedIn <http://ca.linkedin.com/in/barrysteyn>
GitHub <https://github.com/barrysteyn>

**Comment by me4502** [comment]
My patch is just
```
-    path.posix.join("node_modules/next-aws-lambda", "**")
+    path.posix.join("../node_modules/next-aws-lambda", "**")
```
in node_modules/serverless-nextjs-plugin/lib/build.js

**Comment by barrysteyn** [comment]
Would you happen to know why it works on my local deploy
(serverless-offline).

Thanks for this. I'll try it and report back here.


-- 

Barry Steyn
Blog <http://doctrina.org> LinkedIn <http://ca.linkedin.com/in/barrysteyn>
GitHub <https://github.com/barrysteyn>

**Comment by barrysteyn** [comment]
Hi, yes this worked. @danielcondemarin, this definitely seems like a bug

**Comment by barrysteyn** [comment]
@me4502 I submitted a PR to fix this issue. See #127. @me4502 can you do me a favor and test out my PR in your code.

**Comment by franko1260** [comment]
Has/can this be extended so other packages can be included as well? I'm keen on using serverless-http instead of next-aws-lambda. I get a "Cannot find module 'serverless-http'" error when using v2.3.4
