### ISSUE TITLE
Route path returns 404 for nested folder with an index.js file.

### ISSUE THREAD

**Issue by kpaduch** [danielcondemarin/serverless-nextjs-plugin#46]
First of all, thanks for making this awesome serverless plugin! 
I guess this is more of a question since I may be doing something wrong, but my `pages` directory looks like the following:
```
pages
└───home
|   | home.js
|   | home.scss
|   | index.js
└───about
|   | about.js
|   | about.scss
|   | index.js
```

In each of the subdirectory's index.js file, I export the corresponding page. 
When deploying, 4 functions are created:

- `/home`
- `/home/home`
- `/about`
- `/about/about`

The single nested routes return a 404, while the double nested routes return the correct page.
Is this route structure intended? I ask because when running not in serverless mode, nextjs correctly builds only the single nested routes (`/home`, `/about`).

**Comment by danielcondemarin** [comment]
>  I ask because when running not in serverless mode, nextjs correctly builds only the single nested routes (/home, /about).

Are you sure about this? I've created a simple repro [here](https://github.com/danielcondemarin/repro) for:
```
pages
└───blog
|   | blog.js
|   | index.js
```
and `next` builds both `/blog` and `/blog/blog`. 

I'm assuming you only want `/blog` right? If that's the case you have 2 options:
```
pages
└───home
|   | home.scss
|   | index.js
└───about
|   | about.scss
|   | index.js
```
or
```
pages
| home.js
| about.js
```

I wouldn't recommend having your structure because next will try and map any js file under `pages/` to a route, which explains why it builds `/blog` and `/blog/blog`

**Comment by kpaduch** [comment]
Hmm interesting, I updated my packages and seems I was using an old version of next that allowed for that type of structure, but now I do see the double nested routes. I will restructure, thanks for the help anyway. Good to close this issue
